#ifndef itkQuadEdgeMeshEulerOperatorJoinFacetFunctionExplicit_h
#define itkQuadEdgeMeshEulerOperatorJoinFacetFunctionExplicit_h

#include "ITKQuadEdgeMeshExport.h"

#include "itkQuadEdgeMesh.h"

#endif //itkQuadEdgeMeshEulerOperatorJoinFacetFunctionExplicit_h
