#ifndef itkHistogramToLogProbabilityImageFilterExplicit_h
#define itkHistogramToLogProbabilityImageFilterExplicit_h

#include "ITKStatisticsExport.h"

#endif //itkHistogramToLogProbabilityImageFilterExplicit_h
