#ifndef itkHistogramToProbabilityImageFilterExplicit_h
#define itkHistogramToProbabilityImageFilterExplicit_h

#include "ITKStatisticsExport.h"

#endif //itkHistogramToProbabilityImageFilterExplicit_h
