#ifndef itkMahalanobisDistanceThresholdImageFunctionExplicit_h
#define itkMahalanobisDistanceThresholdImageFunctionExplicit_h

#include "ITKImageFunctionExport.h"

#endif //itkMahalanobisDistanceThresholdImageFunctionExplicit_h
