#ifndef itkNeighborhoodOperatorImageFunctionExplicit_h
#define itkNeighborhoodOperatorImageFunctionExplicit_h

#include "ITKImageFunctionExport.h"

#endif //itkNeighborhoodOperatorImageFunctionExplicit_h
