#ifndef itkNearestNeighborInterpolateImageFunctionExplicit_h
#define itkNearestNeighborInterpolateImageFunctionExplicit_h

#include "ITKImageFunctionExport.h"

#endif //itkNearestNeighborInterpolateImageFunctionExplicit_h
