#ifndef itkNearestNeighborExtrapolateImageFunctionExplicit_h
#define itkNearestNeighborExtrapolateImageFunctionExplicit_h

#include "ITKImageFunctionExport.h"

#endif //itkNearestNeighborExtrapolateImageFunctionExplicit_h
