#ifndef itkNeighborhoodBinaryThresholdImageFunctionExplicit_h
#define itkNeighborhoodBinaryThresholdImageFunctionExplicit_h

#include "ITKImageFunctionExport.h"

#endif //itkNeighborhoodBinaryThresholdImageFunctionExplicit_h
