#ifndef itkVectorLinearInterpolateImageFunctionExplicit_h
#define itkVectorLinearInterpolateImageFunctionExplicit_h

#include "ITKImageFunctionExport.h"

#endif //itkVectorLinearInterpolateImageFunctionExplicit_h
