#ifndef itkWindowedSincInterpolateImageFunctionExplicit_h
#define itkWindowedSincInterpolateImageFunctionExplicit_h

#include "ITKImageFunctionExport.h"

#endif //itkWindowedSincInterpolateImageFunctionExplicit_h
