#ifndef itkBSplineExponentialDiffeomorphicTransformExplicit_h
#define itkBSplineExponentialDiffeomorphicTransformExplicit_h

#include "ITKDisplacementFieldExport.h"

#endif //itkBSplineExponentialDiffeomorphicTransformExplicit_h
