#ifndef itkGaussianExponentialDiffeomorphicTransformExplicit_h
#define itkGaussianExponentialDiffeomorphicTransformExplicit_h

#include "ITKDisplacementFieldExport.h"

#endif //itkGaussianExponentialDiffeomorphicTransformExplicit_h
