#ifndef itkTimeVaryingBSplineVelocityFieldTransformExplicit_h
#define itkTimeVaryingBSplineVelocityFieldTransformExplicit_h

#include "ITKDisplacementFieldExport.h"

#endif //itkTimeVaryingBSplineVelocityFieldTransformExplicit_h
