#ifndef itkKittlerIllingworthThresholdImageFilterExplicit_h
#define itkKittlerIllingworthThresholdImageFilterExplicit_h

#include "ITKThresholdingExport.h"

#endif //itkKittlerIllingworthThresholdImageFilterExplicit_h
