#ifndef itkKittlerIllingworthThresholdCalculatorExplicit_h
#define itkKittlerIllingworthThresholdCalculatorExplicit_h

#include "ITKThresholdingExport.h"

#endif //itkKittlerIllingworthThresholdCalculatorExplicit_h
