#ifndef itkMaximumEntropyThresholdImageFilterExplicit_h
#define itkMaximumEntropyThresholdImageFilterExplicit_h

#include "ITKThresholdingExport.h"

#endif //itkMaximumEntropyThresholdImageFilterExplicit_h
