#ifndef itkMaximumEntropyThresholdCalculatorExplicit_h
#define itkMaximumEntropyThresholdCalculatorExplicit_h

#include "ITKThresholdingExport.h"

#endif //itkMaximumEntropyThresholdCalculatorExplicit_h
