#ifndef itkOtsuMultipleThresholdsCalculatorExplicit_h
#define itkOtsuMultipleThresholdsCalculatorExplicit_h

#include "ITKThresholdingExport.h"

#endif //itkOtsuMultipleThresholdsCalculatorExplicit_h
