#ifndef itkRenyiEntropyThresholdImageFilterExplicit_h
#define itkRenyiEntropyThresholdImageFilterExplicit_h

#include "ITKThresholdingExport.h"

#endif //itkRenyiEntropyThresholdImageFilterExplicit_h
