set(DOCUMENTATION "This module contains classes to perform Markov Random Field
classification of image pixels.  An initial label image, perhaps generated by
ITKClassifiers, is improved by iteratively accounting for the spatial coherence
of the labels.")

itk_module(ITKMarkovRandomFieldsClassifiers
  ENABLE_SHARED # ENABLE_SHARED_IF_EXPLICIT_INSTANTIATION
  DEPENDS
    ITKStatistics
    ITKClassifiers
  TEST_DEPENDS
    ITKTestKernel
  DESCRIPTION
    "${DOCUMENTATION}"
)
