#ifndef itkBSplineScatteredDataPointSetToImageFilterExplicit_h
#define itkBSplineScatteredDataPointSetToImageFilterExplicit_h

#include "ITKImageGridExport.h"

#endif //itkBSplineScatteredDataPointSetToImageFilterExplicit_h
