#ifndef itkAnisotropicDiffusionImageFilterExplicit_h
#define itkAnisotropicDiffusionImageFilterExplicit_h

#include "ITKAnisotropicSmoothingExport.h"

#endif //itkAnisotropicDiffusionImageFilterExplicit_h
