#ifndef itkCurvatureAnisotropicDiffusionImageFilterExplicit_h
#define itkCurvatureAnisotropicDiffusionImageFilterExplicit_h

#include "ITKAnisotropicSmoothingExport.h"

#endif //itkCurvatureAnisotropicDiffusionImageFilterExplicit_h
