#ifndef itkCurvatureNDAnisotropicDiffusionFunctionExplicit_h
#define itkCurvatureNDAnisotropicDiffusionFunctionExplicit_h

#include "ITKAnisotropicSmoothingExport.h"

#endif //itkCurvatureNDAnisotropicDiffusionFunctionExplicit_h
