#ifndef itkGradientNDAnisotropicDiffusionFunctionExplicit_h
#define itkGradientNDAnisotropicDiffusionFunctionExplicit_h

#include "ITKAnisotropicSmoothingExport.h"

#endif //itkGradientNDAnisotropicDiffusionFunctionExplicit_h
