#ifndef itkScalarAnisotropicDiffusionFunctionExplicit_h
#define itkScalarAnisotropicDiffusionFunctionExplicit_h

#include "ITKAnisotropicSmoothingExport.h"

#endif //itkScalarAnisotropicDiffusionFunctionExplicit_h
