#ifndef itkFFTNormalizedCorrelationImageFilterExplicit_h
#define itkFFTNormalizedCorrelationImageFilterExplicit_h

#include "ITKConvolutionExport.h"

#endif //itkFFTNormalizedCorrelationImageFilterExplicit_h
