#ifndef itkMaskedFFTNormalizedCorrelationImageFilterExplicit_h
#define itkMaskedFFTNormalizedCorrelationImageFilterExplicit_h

#include "ITKConvolutionExport.h"

#endif //itkMaskedFFTNormalizedCorrelationImageFilterExplicit_h
