#ifndef itkFastMarchingStoppingCriterionBaseExplicit_h
#define itkFastMarchingStoppingCriterionBaseExplicit_h

#include "ITKFastMarchingExport.h"

#endif //itkFastMarchingStoppingCriterionBaseExplicit_h
