#ifndef itkFastMarchingQuadEdgeMeshFilterBaseExplicit_h
#define itkFastMarchingQuadEdgeMeshFilterBaseExplicit_h

#include "ITKFastMarchingExport.h"

#endif //itkFastMarchingQuadEdgeMeshFilterBaseExplicit_h
