#ifndef itkFastMarchingUpwindGradientImageFilterExplicit_h
#define itkFastMarchingUpwindGradientImageFilterExplicit_h

#include "ITKFastMarchingExport.h"

#endif //itkFastMarchingUpwindGradientImageFilterExplicit_h
