#ifndef itkFastMarchingThresholdStoppingCriterionExplicit_h
#define itkFastMarchingThresholdStoppingCriterionExplicit_h

#include "ITKFastMarchingExport.h"

#endif //itkFastMarchingThresholdStoppingCriterionExplicit_h
