#ifndef itkApproximateSignedDistanceMapImageFilterExplicit_h
#define itkApproximateSignedDistanceMapImageFilterExplicit_h

#include "ITKDistanceMapExport.h"

#endif //itkApproximateSignedDistanceMapImageFilterExplicit_h
