#ifndef itkContourDirectedMeanDistanceImageFilterExplicit_h
#define itkContourDirectedMeanDistanceImageFilterExplicit_h

#include "ITKDistanceMapExport.h"

#endif //itkContourDirectedMeanDistanceImageFilterExplicit_h
