#ifndef itkDirectedHausdorffDistanceImageFilterExplicit_h
#define itkDirectedHausdorffDistanceImageFilterExplicit_h

#include "ITKDistanceMapExport.h"

#endif //itkDirectedHausdorffDistanceImageFilterExplicit_h
