#ifndef itkSignedMaurerDistanceMapImageFilterExplicit_h
#define itkSignedMaurerDistanceMapImageFilterExplicit_h

#include "ITKDistanceMapExport.h"

#endif //itkSignedMaurerDistanceMapImageFilterExplicit_h
