#ifndef itkBSplineSyNImageRegistrationMethodExplicit_h
#define itkBSplineSyNImageRegistrationMethodExplicit_h

#include "ITKRegistrationMethodsv4Export.h"

#endif //itkBSplineSyNImageRegistrationMethodExplicit_h
