#ifndef itkLaplacianRecursiveGaussianImageFilterExplicit_h
#define itkLaplacianRecursiveGaussianImageFilterExplicit_h

#include "ITKImageFeatureExport.h"

#endif //itkLaplacianRecursiveGaussianImageFilterExplicit_h
