#ifndef itkLabelOverlapMeasuresImageFilterExplicit_h
#define itkLabelOverlapMeasuresImageFilterExplicit_h

#include "ITKImageStatisticsExport.h"

#endif //itkLabelOverlapMeasuresImageFilterExplicit_h
