#ifndef itkSmoothingRecursiveGaussianImageFilterExplicit_h
#define itkSmoothingRecursiveGaussianImageFilterExplicit_h

#include "ITKSmoothingExport.h"

#endif //itkSmoothingRecursiveGaussianImageFilterExplicit_h
