#ifndef itkProjectedIterativeDeconvolutionImageFilterExplicit_h
#define itkProjectedIterativeDeconvolutionImageFilterExplicit_h

#include "ITKDeconvolutionExport.h"

#include "itkLandweberDeconvolutionImageFilter.h"

#endif //itkProjectedIterativeDeconvolutionImageFilterExplicit_h
