#ifndef itkTikhonovDeconvolutionImageFilterExplicit_h
#define itkTikhonovDeconvolutionImageFilterExplicit_h

#include "ITKDeconvolutionExport.h"

#endif //itkTikhonovDeconvolutionImageFilterExplicit_h
