#include "itkImageRegistrationMethodv4.h"

template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Transform<double, 2u, 2u>, itk::Image<float, 2u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::BSplineSmoothingOnUpdateDisplacementFieldTransform<double, 2u>, itk::Image<double, 2u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::GaussianExponentialDiffeomorphicTransform<double, 3u>, itk::Image<double, 3u> >; //Instantiated 9 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::TimeVaryingBSplineVelocityFieldTransform<double, 3u>, itk::Image<double, 3u> >; //Instantiated 9 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::DisplacementFieldTransform<double, 3u>, itk::Image<double, 3u> >; //Instantiated 12 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::AffineTransform<double, 3u>, itk::Image<double, 3u> >; //Instantiated 33 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::DisplacementFieldTransform<double, 2u>, itk::Image<double, 2u> >; //Instantiated 9 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::GaussianSmoothingOnUpdateDisplacementFieldTransform<double, 2u>, itk::Image<double, 2u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Euler2DTransform<double>, itk::Image<double, 2u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::BSplineTransform<double, 2u, 3u>, itk::Image<double, 2u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::BSplineExponentialDiffeomorphicTransform<double, 3u>, itk::Image<double, 3u> >; //Instantiated 9 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform<double, 3u>, itk::Image<double, 3u> >; //Instantiated 9 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::BSplineExponentialDiffeomorphicTransform<double, 2u>, itk::Image<double, 2u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::GaussianExponentialDiffeomorphicTransform<double, 2u>, itk::Image<double, 2u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform<double, 2u>, itk::Image<double, 2u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::BSplineTransform<double, 3u, 3u>, itk::Image<double, 3u> >; //Instantiated 9 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Euler3DTransform<double>, itk::Image<double, 3u> >; //Instantiated 9 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Similarity3DTransform<double>, itk::Image<double, 3u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::TranslationTransform<double, 3u>, itk::Image<double, 3u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Transform<double, 3u, 3u>, itk::Image<float, 3u> >; //Instantiated 6 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::GaussianSmoothingOnUpdateDisplacementFieldTransform<double, 3u>, itk::Image<double, 3u> >; //Instantiated 9 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::AffineTransform<double, 2u>, itk::Image<double, 2u> >; //Instantiated 30 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::BSplineSmoothingOnUpdateDisplacementFieldTransform<double, 3u>, itk::Image<double, 3u> >; //Instantiated 9 times
template class ITKRegistrationMethodsv4_EXPORT itk::ImageRegistrationMethodv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::TimeVaryingBSplineVelocityFieldTransform<double, 2u>, itk::Image<double, 2u> >; //Instantiated 6 times
