#ifndef itkVoronoiSegmentationImageFilterBaseExplicit_h
#define itkVoronoiSegmentationImageFilterBaseExplicit_h

#include "ITKVoronoiExport.h"

#endif //itkVoronoiSegmentationImageFilterBaseExplicit_h
