#ifndef itkNeighborhoodOperatorImageFilterExplicit_h
#define itkNeighborhoodOperatorImageFilterExplicit_h

#include "ITKImageFilterBaseExport.h"

#endif //itkNeighborhoodOperatorImageFilterExplicit_h
