#ifndef itkVectorNeighborhoodOperatorImageFilterExplicit_h
#define itkVectorNeighborhoodOperatorImageFilterExplicit_h

#include "ITKImageFilterBaseExport.h"

#endif //itkVectorNeighborhoodOperatorImageFilterExplicit_h
