#include "itkConstNeighborhoodIterator.h"

template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<unsigned short, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<unsigned short, 3u>, itk::VectorImage<unsigned short, 3u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<double, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<double, 3u>, itk::Image<double, 3u> > >; //Instantiated 464 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned long, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned long, 2u>, itk::Image<unsigned long, 2u> > >; //Instantiated 229 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<short, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<short, 2u>, itk::Image<short, 2u> > >; //Instantiated 405 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<signed char, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<signed char, 3u>, itk::VectorImage<signed char, 3u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<float, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<float, 2u>, itk::Image<float, 2u> > >; //Instantiated 666 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Vector<float, 3u>, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Vector<float, 3u>, 3u>, itk::Image<itk::Vector<float, 3u>, 3u> > >; //Instantiated 81 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<signed char, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<signed char, 3u>, itk::Image<signed char, 3u> > >; //Instantiated 438 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<unsigned short, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<unsigned short, 2u>, itk::VectorImage<unsigned short, 2u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<unsigned char, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<unsigned char, 3u>, itk::VectorImage<unsigned char, 3u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<long, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<long, 3u>, itk::Image<long, 3u> > >; //Instantiated 206 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<char, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<char, 2u>, itk::Image<char, 2u> > >; //Instantiated 46 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<bool, 1u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<bool, 1u>, itk::Image<bool, 1u> > >; //Instantiated 12 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<int, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<int, 3u>, itk::VectorImage<int, 3u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<unsigned int, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<unsigned int, 2u>, itk::VectorImage<unsigned int, 2u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<double, 4u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<double, 4u>, itk::Image<double, 4u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Vector<float, 3u>, 4u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Vector<float, 3u>, 4u>, itk::Image<itk::Vector<float, 3u>, 4u> > >; //Instantiated 11 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned short, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned short, 2u>, itk::Image<unsigned short, 2u> > >; //Instantiated 431 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Vector<double, 2u>, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Vector<double, 2u>, 2u>, itk::Image<itk::Vector<double, 2u>, 2u> > >; //Instantiated 71 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Vector<double, 2u>, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Vector<double, 2u>, 3u>, itk::Image<itk::Vector<double, 2u>, 3u> > >; //Instantiated 22 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<float, 3u>, itk::ConstantBoundaryCondition<itk::Image<float, 3u>, itk::Image<float, 3u> > >; //Instantiated 72 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned int, 4u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned int, 4u>, itk::Image<unsigned int, 4u> > >; //Instantiated 9 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<long, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<long, 2u>, itk::Image<long, 2u> > >; //Instantiated 430 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned int, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned int, 3u>, itk::Image<unsigned int, 3u> > >; //Instantiated 424 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<float, 4u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<float, 4u>, itk::Image<float, 4u> > >; //Instantiated 16 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Vector<float, 2u>, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Vector<float, 2u>, 3u>, itk::Image<itk::Vector<float, 2u>, 3u> > >; //Instantiated 13 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<short, 3u>, itk::ConstantBoundaryCondition<itk::Image<short, 3u>, itk::Image<short, 3u> > >; //Instantiated 15 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned char, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned char, 2u>, itk::Image<unsigned char, 2u> > >; //Instantiated 606 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<short, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<short, 3u>, itk::Image<short, 3u> > >; //Instantiated 424 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Vector<double, 3u>, 4u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Vector<double, 3u>, 4u>, itk::Image<itk::Vector<double, 3u>, 4u> > >; //Instantiated 15 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<signed char, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<signed char, 2u>, itk::VectorImage<signed char, 2u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<short, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<short, 3u>, itk::VectorImage<short, 3u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<long, 1u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<long, 1u>, itk::Image<long, 1u> > >; //Instantiated 222 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<bool, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<bool, 3u>, itk::Image<bool, 3u> > >; //Instantiated 152 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned char, 1u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned char, 1u>, itk::Image<unsigned char, 1u> > >; //Instantiated 12 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<int, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<int, 3u>, itk::Image<int, 3u> > >; //Instantiated 420 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<double, 3u>, itk::ConstantBoundaryCondition<itk::Image<double, 3u>, itk::Image<double, 3u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<signed char, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<signed char, 2u>, itk::Image<signed char, 2u> > >; //Instantiated 491 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<bool, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<bool, 2u>, itk::Image<bool, 2u> > >; //Instantiated 113 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<double, 2u>, itk::ConstantBoundaryCondition<itk::Image<double, 2u>, itk::Image<double, 2u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<float, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<float, 3u>, itk::Image<float, 3u> > >; //Instantiated 605 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<float, 2u>, itk::ConstantBoundaryCondition<itk::Image<float, 2u>, itk::Image<float, 2u> > >; //Instantiated 8 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<int, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<int, 2u>, itk::Image<int, 2u> > >; //Instantiated 419 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<float, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<float, 3u>, itk::VectorImage<float, 3u> > >; //Instantiated 14 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned char, 3u>, itk::ConstantBoundaryCondition<itk::Image<unsigned char, 3u>, itk::Image<unsigned char, 3u> > >; //Instantiated 7 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<double, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<double, 2u>, itk::VectorImage<double, 2u> > >; //Instantiated 12 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned char, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned char, 3u>, itk::Image<unsigned char, 3u> > >; //Instantiated 568 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<double, 6u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<double, 6u>, itk::Image<double, 6u> > >; //Instantiated 261 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned int, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned int, 2u>, itk::Image<unsigned int, 2u> > >; //Instantiated 428 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::FixedArray<unsigned char, 4u>, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::FixedArray<unsigned char, 4u>, 3u>, itk::Image<itk::FixedArray<unsigned char, 4u>, 3u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Index<4u>, 4u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Index<4u>, 4u>, itk::Image<itk::Index<4u>, 4u> > >; //Instantiated 10 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned short, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned short, 3u>, itk::Image<unsigned short, 3u> > >; //Instantiated 470 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<unsigned char, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<unsigned char, 2u>, itk::VectorImage<unsigned char, 2u> > >; //Instantiated 8 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<double, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<double, 3u>, itk::VectorImage<double, 3u> > >; //Instantiated 12 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<int, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<int, 2u>, itk::VectorImage<int, 2u> > >; //Instantiated 12 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::RGBPixel<float>, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::RGBPixel<float>, 2u>, itk::Image<itk::RGBPixel<float>, 2u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<unsigned int, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<unsigned int, 3u>, itk::VectorImage<unsigned int, 3u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<unsigned long, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<unsigned long, 3u>, itk::Image<unsigned long, 3u> > >; //Instantiated 212 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Vector<float, 3u>, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Vector<float, 3u>, 2u>, itk::Image<itk::Vector<float, 3u>, 2u> > >; //Instantiated 10 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<float, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<float, 2u>, itk::VectorImage<float, 2u> > >; //Instantiated 14 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::VectorImage<short, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::VectorImage<short, 2u>, itk::VectorImage<short, 2u> > >; //Instantiated 6 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Vector<float, 2u>, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Vector<float, 2u>, 2u>, itk::Image<itk::Vector<float, 2u>, 2u> > >; //Instantiated 49 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<itk::Vector<double, 3u>, 3u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<itk::Vector<double, 3u>, 3u>, itk::Image<itk::Vector<double, 3u>, 3u> > >; //Instantiated 56 times
template class ITKCommon_EXPORT itk::ConstNeighborhoodIterator<itk::Image<double, 2u>, itk::ZeroFluxNeumannBoundaryCondition<itk::Image<double, 2u>, itk::Image<double, 2u> > >; //Instantiated 490 times
