#include "itkBinaryMorphologyImageFilter.h"

template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<signed char, 2u>, itk::Image<signed char, 2u>, itk::FlatStructuringElement<2u> >; //Instantiated 18 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned char, 2u>, itk::Image<unsigned char, 2u>, itk::FlatStructuringElement<2u> >; //Instantiated 39 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned char, 1u>, itk::Image<unsigned char, 1u>, itk::FlatStructuringElement<1u> >; //Instantiated 12 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned char, 3u>, itk::Image<unsigned char, 3u>, itk::BinaryBallStructuringElement<unsigned char, 3u, itk::NeighborhoodAllocator<unsigned char> > >; //Instantiated 12 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned int, 3u>, itk::Image<unsigned int, 3u>, itk::FlatStructuringElement<3u> >; //Instantiated 18 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned short, 2u>, itk::Image<unsigned short, 2u>, itk::BinaryBallStructuringElement<unsigned short, 2u, itk::NeighborhoodAllocator<unsigned short> > >; //Instantiated 15 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::BinaryBallStructuringElement<float, 2u, itk::NeighborhoodAllocator<float> > >; //Instantiated 9 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned short, 2u>, itk::Image<unsigned char, 2u>, itk::BinaryBallStructuringElement<unsigned short, 2u, itk::NeighborhoodAllocator<unsigned short> > >; //Instantiated 6 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<int, 2u>, itk::Image<int, 2u>, itk::FlatStructuringElement<2u> >; //Instantiated 18 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<short, 2u>, itk::Image<short, 2u>, itk::FlatStructuringElement<2u> >; //Instantiated 18 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned short, 3u>, itk::Image<unsigned short, 3u>, itk::BinaryBallStructuringElement<unsigned short, 3u, itk::NeighborhoodAllocator<unsigned short> > >; //Instantiated 48 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned short, 3u>, itk::Image<unsigned short, 3u>, itk::FlatStructuringElement<3u> >; //Instantiated 18 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned char, 2u>, itk::Image<unsigned char, 2u>, itk::BinaryBallStructuringElement<bool, 2u, itk::NeighborhoodAllocator<bool> > >; //Instantiated 6 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<short, 3u>, itk::Image<short, 3u>, itk::FlatStructuringElement<3u> >; //Instantiated 18 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned short, 2u>, itk::Image<unsigned short, 2u>, itk::FlatStructuringElement<2u> >; //Instantiated 18 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned char, 2u>, itk::Image<unsigned char, 2u>, itk::BinaryBallStructuringElement<unsigned char, 2u, itk::NeighborhoodAllocator<unsigned char> > >; //Instantiated 27 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<int, 3u>, itk::Image<int, 3u>, itk::FlatStructuringElement<3u> >; //Instantiated 18 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned char, 3u>, itk::Image<unsigned char, 3u>, itk::FlatStructuringElement<3u> >; //Instantiated 21 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::BinaryBallStructuringElement<float, 3u, itk::NeighborhoodAllocator<float> > >; //Instantiated 6 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<unsigned int, 2u>, itk::Image<unsigned int, 2u>, itk::FlatStructuringElement<2u> >; //Instantiated 18 times
template class ITKBinaryMathematicalMorphology_EXPORT itk::BinaryMorphologyImageFilter<itk::Image<signed char, 3u>, itk::Image<signed char, 3u>, itk::FlatStructuringElement<3u> >; //Instantiated 18 times
