#ifndef itkVectorIndexSelectionCastImageFilterExplicit_h
#define itkVectorIndexSelectionCastImageFilterExplicit_h

#include "ITKImageIntensityExport.h"

#endif //itkVectorIndexSelectionCastImageFilterExplicit_h
