#ifndef itkGradientRecursiveGaussianImageFilterExplicit_h
#define itkGradientRecursiveGaussianImageFilterExplicit_h

#include "ITKImageGradientExport.h"

#endif //itkGradientRecursiveGaussianImageFilterExplicit_h
