#ifndef itkGradientMagnitudeRecursiveGaussianImageFilterExplicit_h
#define itkGradientMagnitudeRecursiveGaussianImageFilterExplicit_h

#include "ITKImageGradientExport.h"

#endif //itkGradientMagnitudeRecursiveGaussianImageFilterExplicit_h
