#ifndef itkRegularStepGradientDescentOptimizerv4Explicit_h
#define itkRegularStepGradientDescentOptimizerv4Explicit_h

#include "ITKOptimizersv4Export.h"

#endif //itkRegularStepGradientDescentOptimizerv4Explicit_h
