#ifndef itkRegularStepGradientDescentOptimizerv4Explicit_h
#define itkRegularStepGradientDescentOptimizerv4Explicit_h

#include "ITKOptimizersv4Export.h"

ITK_TEMPLATE_INSTANTIATION_EXTERN template class itk::RegularStepGradientDescentOptimizerv4<double>; //Instantiated 6 times
#endif //itkRegularStepGradientDescentOptimizerv4Explicit_h
