#ifndef itkBinaryMinMaxCurvatureFlowFunctionExplicit_h
#define itkBinaryMinMaxCurvatureFlowFunctionExplicit_h

#include "ITKCurvatureFlowExport.h"

#endif //itkBinaryMinMaxCurvatureFlowFunctionExplicit_h
