#ifndef itkBinaryMinMaxCurvatureFlowImageFilterExplicit_h
#define itkBinaryMinMaxCurvatureFlowImageFilterExplicit_h

#include "ITKCurvatureFlowExport.h"

#endif //itkBinaryMinMaxCurvatureFlowImageFilterExplicit_h
