#ifndef itkBSplineTransformParametersAdaptorExplicit_h
#define itkBSplineTransformParametersAdaptorExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkBSplineTransformParametersAdaptorExplicit_h
