#ifndef itkConstantVelocityFieldTransformParametersAdaptorExplicit_h
#define itkConstantVelocityFieldTransformParametersAdaptorExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkConstantVelocityFieldTransformParametersAdaptorExplicit_h
