#ifndef itkGaussianExponentialDiffeomorphicTransformParametersAdaptorExplicit_h
#define itkGaussianExponentialDiffeomorphicTransformParametersAdaptorExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkGaussianExponentialDiffeomorphicTransformParametersAdaptorExplicit_h
