#ifndef itkImageToSpatialObjectRegistrationMethodExplicit_h
#define itkImageToSpatialObjectRegistrationMethodExplicit_h

#include "ITKRegistrationCommonExport.h"

#include "itkGroupSpatialObject.h"

#endif //itkImageToSpatialObjectRegistrationMethodExplicit_h
