#ifndef itkMatchCardinalityImageToImageMetricExplicit_h
#define itkMatchCardinalityImageToImageMetricExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkMatchCardinalityImageToImageMetricExplicit_h
