#ifndef itkMattesMutualInformationImageToImageMetricExplicit_h
#define itkMattesMutualInformationImageToImageMetricExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkMattesMutualInformationImageToImageMetricExplicit_h
