#ifndef itkMultiResolutionImageRegistrationMethodExplicit_h
#define itkMultiResolutionImageRegistrationMethodExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkMultiResolutionImageRegistrationMethodExplicit_h
