#ifndef itkMutualInformationImageToImageMetricExplicit_h
#define itkMutualInformationImageToImageMetricExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkMutualInformationImageToImageMetricExplicit_h
