#ifndef itkMeanSquareRegistrationFunctionExplicit_h
#define itkMeanSquareRegistrationFunctionExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkMeanSquareRegistrationFunctionExplicit_h
