#ifndef itkMultiResolutionPyramidImageFilterExplicit_h
#define itkMultiResolutionPyramidImageFilterExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkMultiResolutionPyramidImageFilterExplicit_h
