#ifndef itkNormalizedCorrelationImageToImageMetricExplicit_h
#define itkNormalizedCorrelationImageToImageMetricExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkNormalizedCorrelationImageToImageMetricExplicit_h
