#ifndef itkPointSetToPointSetRegistrationMethodExplicit_h
#define itkPointSetToPointSetRegistrationMethodExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkPointSetToPointSetRegistrationMethodExplicit_h
