#ifndef itkRecursiveMultiResolutionPyramidImageFilterExplicit_h
#define itkRecursiveMultiResolutionPyramidImageFilterExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkRecursiveMultiResolutionPyramidImageFilterExplicit_h
