#ifndef itkTimeVaryingVelocityFieldTransformParametersAdaptorExplicit_h
#define itkTimeVaryingVelocityFieldTransformParametersAdaptorExplicit_h

#include "ITKRegistrationCommonExport.h"

#endif //itkTimeVaryingVelocityFieldTransformParametersAdaptorExplicit_h
