#ifndef itkMultiResolutionPDEDeformableRegistrationExplicit_h
#define itkMultiResolutionPDEDeformableRegistrationExplicit_h

#include "ITKPDEDeformableRegistrationExport.h"

#endif //itkMultiResolutionPDEDeformableRegistrationExplicit_h
